In [77]:
import numpy as np
import pandas as pd
df = pd.read_csv('data/train_tfidf_features.csv')



In [78]:
test = df.to_numpy()
y = test[1:,1]
X = test[1:,2:]
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
def sigmoid(z):
    return 1.0/(1 + np.exp(-z))

def loss_log(y,y_hat):
    
    return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

def gradients(X, y, y_hat):
    m = X.shape[0]
    dw = 1/m * np.dot(X.T, (y_hat - y))
    db = np.mean(y_hat - y)

    return dw, db   

    return X

def train(X, y, bs, epochs, lr):

    # X --> Input.
    # y --> true/target value.
    # bs --> Batch Size.
    # epochs --> Number of iterations.
    # lr --> Learning rate.

    # m-> number of training examples
    # n-> number of features 
    m, n = X.shape

    # Initializing weights and bias to zeros.
    w = np.zeros((n,1))
    b = 0

    # Reshaping y.
    y = y.reshape(m,1)

    # Normalizing the inputs.
    

    # Empty list to store losses.
    losses = []

    # Training loop.
    for epoch in range(epochs):
        for i in range((m-1)//bs + 1):

            # Defining batches. SGD.
            start_i = i*bs
            end_i = start_i + bs
            xb = X[start_i:end_i]
            yb = y[start_i:end_i]

            # Calculating hypothesis/prediction.
            y_hat = sigmoid(np.dot(xb, w) + b)

            # Getting the gradients of loss w.r.t parameters.
            dw, db = gradients(xb, yb, y_hat)

            # Updating the parameters.
            w -= lr*dw
            b -= lr*db

        # Calculating loss and appending it in the list.
        l = loss_log(y, sigmoid(np.dot(X, w) + b))

        losses.append(l)

    # returning weights, bias and losses(List).
    return w, b, losses

In [80]:
weights, bias,losses = train(X, y,bs=100, lr=0.01, epochs=1000)


print("Weights:", weights)
print("Bias:", bias)    
print("Losses:", losses[-1])
def predict(X, weights, bias):
    z = np.dot(X, weights) + bias
    y_hat = sigmoid(z)
    return np.round(y_hat)

KeyboardInterrupt: 